engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
  markdownlint:
    enabled: true
ratings:
  paths:
    - "routes/"
    - "listings/"
    - "src/scripts/"
    - "src/styles/"
    - "**.md"
exclude_paths:
  - "test/"
  - "public/"
  - "docs/"
  - "db/"
