engines:
  eslint:
    enabled: true
    checks:
      global-require:
        enabled: false
      no-path-concat:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
        javascript:
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: false
ratings:
  paths:
    - "routes/"
    - "listings/"
    - "src/scripts/"
    - "src/styles/"
    - "**.md"
exclude_paths:
  - "test/"
  - "public/"
  - "docs/"
  - "db/"
