language: node_js
node_js: '6'
install: npm install -g mocha; npm install chai; npm install -g codeclimate-test-reporter; npm install

env:
  global:
    - secure: VXV6LSJhGRYVCSauOyvy+4FLKdxM6OGjcZ1Ur62RkkiIHiK8rE/ib3ZE2Ah2AVvRozXi47tXgeHn3LkmqmhzSPuagZNLLCldOJ8W9xr11WqvdWgygVRV6O4Cs8jjLH+OMMXgrraONevIw4/LRGgWWUYOy6R4AixPf6C1mEz5lJi7ygysILBKBfPrHJSRhwwTZwth8nj6iiWz1WIAXxYetRU12619moWp/NWitVkYAwgyDKnr9sRuDL9QDkuqYDuRqp5LSW5rb2zQq3U035NfqM/qZwzpoj8mHfrE88pshq3KYWdLp475HpHIiwi1mTm9UHS+gq4WZlFROlCPVViEvCpaM8j6QIBXqLP55ddn6epEpUnJBV7oGPE3hlahTXuJxca7SwMIZNSSS6inMKZZJQBMkeugrtH1WvPXdMH55BOleuRrsY3Zq5jDyI8dg+zw4ZOJzotQKbdKIgsUeID5JEd6JxWzF6JKdFn8FkRn5NGrXf7DN7XiM2sNXumsuIz58+/8sIsLkxtDe0pZ2/POw+XFiMePpb//MO8kWWfHsWyKnLzT8zW4Ckb56f07cJ9sXnQbORSMVwJZzp0DmvXYETYrSVF1bRZExfmoXGGNVeprfD/hQJ9LMJ9Y7+8D4W1WnFjZ09y7H1OGRPKNIEzAZ9ZwEM8dv19gVyF2HZUy+AU=
    - secure: XN55WIkbe5NhnESMlTzUfoRjwXHC4UmffjNRG7aBSfba12hK7wik8bWOuSF3ET/DKzwL1cdGREZxDIfOYLfo8XWUht6OBobiZG5hGvf8Q34XBn7+XGbubPdBB+3iC2OTowEKn1LRP9yfEjlTrd1p7AxchqaxPulWeKgEI7iltqnxx/f0NkF0VwLsnB5LaDjDTZUpS6fo1sVpXGKkgWARxVrjVavH52hvAFOPCB5bym+kbnGRPFudtRTqdhhHtoyhYtFZTxPtT3g0fTQ2/ee+Ci1lFKpsYXT8hkcRLwSjNZcW/vovUkL9w12OHLAijFzuOcyaPC0hb7aSVsqhX/ctaKlyeeikiVYI3oO8vE9is01yaunMEt3Kc0M/LyHdEK7LQiPj2QSHJ+pn1dTivJhjeGizIAUewT3xC7g0+qUCHa/DWiQOivBd33q8ikE6OlqZ0jzdOPTFmPGKEzAjVydCDt8I3/FxbBL6XJP4MYtQdmX6PQ+9kUZHkUIyQ3eHQB1/a7f9a4e+4pGkjKAnY0tt4qinQt3n0H230BU3L4j+GzmrbzIMjqcxyEICIJofPHxI+aPKAbdEtNai4JCvYwXpnEsYAzuetx/You+RJoAgT/4lATckzKh9oiRgKUkhg2x4F3ECOqwotfwEEwaVgiuKjSD0aJp4JTalpHX2kEhvrS8=

addons:
  code_climate:
    repo_token: f16cbb3c3202ee9f72e0ac789746118cf168f067e1cf52d943f68b76a801cac5
after_success:
  - codeclimate-test-reporter < lcov.info
